# default-config.yaml

goes_first: player_a  # player_a, player_b, random
outputDIR: data
player_a:
  deckPath: decks/UWTempo.dck
  type: mcts


  priors:
    priority: false
    target: false
    binary: false
    opponent: false

  noise:
    enabled: false

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    c_puct: 1.0 #does nothing
    td_discount: 0.95

  mulligans:
    enabled: false

player_b:
  deckPath: decks/Standard-MonoG.dck
  type: mcts

  priors:
    priority: false
    target: false
    binary: false
    opponent: false

  noise:
    enabled: false

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    c_puct: 1.0 #does nothing
    td_discount: 0.95

  mulligans:
    enabled: false

training:
  games: 5
  threads: 4
  max_turns: 50 #does nothing

server:
  host: localhost
  port: 50052
  opponent_port: 50053

logging:
  log_feature_hash: true
  save_final_wr: true
  show_wr: true #does nothing